GET http://localhost:3000/vehiculos/find?marca=Acura

###

GET http://localhost:3000/vehiculos/find?ano=1996

###

GET http://localhost:3000/vehiculos/find?marca=Fiat

###

GET http://localhost:3000/vehiculos/find?marca=Acura&ano=1996

###

GET http://localhost:3000/vehiculos/find?marca=Acurã&ano=2010